mariadb:
  image: jinwoo/mariadb:10.3
#  command: bash -c "while [ 0 ]; do sleep 1;done"
#  volumes:
#    - ./initdb:/docker-entrypoint-initdb.d
#    - /etc/localtime:/etc/localtime:ro
  expose:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: apiserver
    MYSQL_USER: apiserver_user
    MYSQL_PASSWORD: apiserver_pass
    MYSQL_IMPORT_SQL: |
        grant all privileges on *.* to apiserver_user@'%';
